# Generated by Django 5.0.2 on 2024-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Acoustic', 'Acoustic'), ('Ambient', 'Ambient'), ('Classical', 'Classical'), ('Instrumental', 'Instrumental'), ('Jazz', 'Jazz')], max_length=100)),
                ('performer', models.CharField(default='', max_length=100)),
                ('ratings', models.CharField(default='', max_length=100)),
                ('day', models.CharField(default='', max_length=100)),
                ('rest_image', models.ImageField(default='', upload_to='restaurant')),
            ],
        ),
    ]
