# Generated by Django 5.0.2 on 2024-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('performer', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField()),
                ('rest_image', models.ImageField(default='', upload_to='restaurant')),
            ],
        ),
    ]
