# Generated by Django 5.0.2 on 2024-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
