# Generated by Django 5.0.2 on 2024-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_restaurant_end_time_restaurant_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='start_time',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
