# Generated by Django 5.0.2 on 2024-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_restaurant_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Acoustic', 'Acoustic'), ('Ambient', 'Ambient'), ('Classical', 'Classical'), ('Instrumental', 'Instrumental'), ('Jazz', 'Jazz')], default='', max_length=100),
        ),
    ]
