# Generated by Django 5.0.2 on 2024-03-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_restaurant_ratings_alter_restaurant_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
