# Generated by Django 5.0.2 on 2024-03-07 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ratingreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RatingReview',
            new_name='Rating',
        ),
    ]
