# Generated by Django 5.0.2 on 2024-03-07 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_ratingreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rated_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
