# Generated by Django 5.0.2 on 2024-03-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rating_rated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
    ]
