# Generated by Django 5.0.2 on 2024-03-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_rating_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ratings',
        ),
    ]
