# Generated by Django 5.0.2 on 2024-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_restaurant_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ratings',
            field=models.CharField(default='', max_length=100),
        ),
    ]
