# Generated by Django 5.0.2 on 2024-03-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rating_review_desp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ratings',
        ),
    ]
