# Generated by Django 5.0.2 on 2024-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
