# Generated by Django 5.0.2 on 2024-03-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_restaurant_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated_date',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='review_desp',
        ),
    ]
